### ISSUE TITLE
Tag Suggestion Component  / Cannot read properties of null (reading 'tagName')

### ISSUE THREAD

**Issue by tsugawa** [jsuites/jsuites#121]
This problem occurs in the component implementation, and also in the example page.

https://jsuites.net/v4/javascript-tags/remote-search

Console message:

jsuites.js:10143 Uncaught TypeError: Cannot read properties of null (reading 'tagName')
    at jSuites.search.obj.keyup (jsuites.js:10143:35)
    at HTMLDivElement.tagsKeyUp (jsuites.js:11603:24)
jSuites.search.obj.keyup @ jsuites.js:10143
tagsKeyUp @ jsuites.js:11603

**Comment by tsugawa** [comment]
I fixed adding this line.

![image](https://user-images.githubusercontent.com/8302404/183231357-aa17b52c-1f51-414a-8dd8-73fe09b7f8f0.png)

**Comment by ntbatyr** [comment]
Hi, `options.input` is null. How I can set it a value, and what i have to pass. Have I create some element or else.
